services:
  dv-auto:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: dv-auto

    restart: unless-stopped
    init: true

    environment:
      DV_USER: ${DV_USER}
      DV_PASS: ${DV_PASS}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      NODE_ENV: production
      TZ: Asia/Seoul
      HEADLESS: "true"
      SQLITE_DB_PATH: /app/runtime-data/app.db

    volumes:
      - /opt/dv-auto/data:/app/runtime-data

    stop_grace_period: 30s
