name: Run Macro

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-macro:
    if: secrets.RUN_WORKFLOW == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Cache Playwright Browsers
        id: cache-playwright-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}-${{ matrix.node-version }}
          restore-keys: |
            ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps


      - name: Run macro.js
        run: node macro.js
        env:
          DV_USER: ${{ secrets.DV_USER }}
          DV_PASS: ${{ secrets.DV_PASS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
